POST /api/users/register HTTP/1.1
Host: localhost:9090
Content-Type: application/json
Content-Length: 96

{
  "name":"adu--test",
  "username": "adu_test",
  "email": "adu@example.com",
  "password": "123456"
}

###
POST /api/users/login HTTP/1.1
Host: localhost:9090
Content-Type: application/json
Content-Length: 52

{
  "email": "adu@example.com",
  "password": "123456"
}

###
POST /api/users/get_user_and_profile HTTP/1.1
Host: localhost:9090
Content-Type: application/json
Content-Length: 52

{
  "token": "5f4fb73b4f5dc2e8dc25830c84e7af8f456a071ea5dcf16678e1ea5951293c18" 
}

###
POST /api/users/update_profile_data HTTP/1.1
Host: localhost:9090
Content-Type: application/json
Content-Length: 52

{
  "token": "f0cc59de4b47184e5b4ba6835a22cbda535c09562da9e11749b2b4ab31176b57",
  "name":"adu--test-updated",
  "username": "adu_test_updated"
}
